[package]
name = "chactivityserver"
version = "0.1.0"
authors = ["Sébastien (AmarOk) Blin"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.1"
chrono = "0.4"
regex = "1.7.0"
reqwest = "0.11.13"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"